adding links to all blog posts in the home page #48
mmavroudi/Blog pull request #50
Opened 2023-01-03 15:20 UTC by mmavroudi

2023-01-04 14:34 UTC, kkampardi requested changes
It is functional but need to update the home urls

2023-01-04 14:34 UTC, kkampardi commented on projects/templates/home.html
> +              <a href="{{ rand_post.slug }}"><img src="{{ MEDIA_URL }}{{ rand_post.image }}" alt="" class="img-fluid"></a>
Always use a  [url tag](https://docs.djangoproject.com/en/4.1/ref/templates/builtins/#url)  in href in django templates. 
Need to update all the instances that use slug in the href in this file
**To use slug in the href tag is not a good practice, can cause issues in the future.**

2023-01-04 14:34 UTC, kkampardi commented on projects/templates/home.html
> +              <a href="{{ rand_post.slug }}"><img src="{{ MEDIA_URL }}{{ rand_post.image }}" alt="" class="img-fluid"></a>
@mmavroudi

2023-01-05 13:56 UTC, mmavroudi commented
I don't know if this is the right way of using url tags. It was a bit difficult to understand how I would take the specific url with the specific slug each time and I came across with this solution in stackoverflow. Is it ok?

2023-01-06 09:32 UTC, kkampardi approved these changes

2023-01-06 09:33 UTC, merged